# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 22:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('age', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='individual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CaseReporter.Individual'),
        ),
    ]
